### ISSUE TITLE
One bot to rule them all

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/Mastodon-Bot#2]
Ultimately these examples that will live in https://github.com/CodingTrain/website, but here I'd like to combine them all as one bot that I can deploy and leave running for testing and fun times. 🦄

**Comment by danielflataker** [comment]
I think a good way to do it would be to make a new folder in the repo (maybe called "Bot" or something?) and then one can start commit to the new bot folder, and implement the features from all the bots. Open for opinions.
